### ISSUE TITLE
Publish extension to codium marketplace (open VSX)

### ISSUE THREAD

**Issue by felixsanz** [setek/vscode-sort-selection-concentrically#19]
Please! Can't live without this extension xD Can you publish it to the codium marketplace?

https://open-vsx.org/
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by roubaobaozi** [comment]
Hi! I'm glad you like the extension!

I have taken a look at publishing it elsewhere, but it might take me some time, it looks like I need to update sections of the extension before I can do that.

I'll update here when I figure something out :)

**Comment by roubaobaozi** [comment]
Hi :)

So I've done .. something. I'm waiting on Eclipse to verify my namespace or something?

https://open-vsx.org/extension/baobaozi/sort-selection-concentrically

I'm not entirely sure if it's available to use or it needs to wait for the verification. But let me know if you are able to install it already.

HTH!

**Comment by felixsanz** [comment]
> Hi :)
> 
> So I've done .. something. I'm waiting on Eclipse to verify my namespace or something?
> 
> https://open-vsx.org/extension/baobaozi/sort-selection-concentrically
> 
> I'm not entirely sure if it's available to use or it needs to wait for the verification. But let me know if you are able to install it already.
> 
> HTH!

it works! I'm able to install it and works fine. Thanks so much!
