### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by saudes77** [setek/vscode-sort-selection-concentrically#3]
I just installed this extension for VS Code and after closing and re-opening the program I tried selecting some CSS and running the "Sort CSS properties concentrically (undefined to bottom)" command from the command palette.
I got the following error:

command 'sortConcentrically.sortConcentrically' not found

Not sure if this is a bug, or if maybe I am missing some configuration?

**Comment by roubaobaozi** [comment]
Hi @saudes77, did you hit the Reload button after installing? Or do you mean you restarted VS Code itself? I’ve had a report of someone else having this same issue, though after a little while (perhaps another restart) it rights itself. Probably hadn’t finished installing the extension. Could you try again (maybe uninstalling and reinstalling, reloading, too) and let me know?

**Comment by saudes77** [comment]
@setek Thanks for the quick response!
I meant that I restarted VS Code.

Tried your suggestion: I uninstalled the extension, then reinstalled it and hit "reload." That didn't work so I restarted VS Code again and still the same issue.

**Comment by roubaobaozi** [comment]
Hi @saudes77!

Hmm that’s not good. Could you give me some more information please?

What version of vs code, what OS, etc.?

**Comment by saudes77** [comment]
MacOS High Sierra 10.13.6
VS Code 1.23.1

**Comment by roubaobaozi** [comment]
VS Code 1.25.1 is out; would you mind upgrading and trying again please?

**Comment by saudes77** [comment]
Sorry for the delay.
I updated to 1.25.1 and I'm still getting the same error. I also tried disabling all other extensions (and reloading) and re-attempted to uninstall/re-install your extension and still the same results.

**Comment by RubenSibon** [comment]
Hi, I have the exact same issue. I tried reinstalling and restarting VS Code in between, but that doesn't help sadly.

I am using **VS Code 1.26.1** on **Ubuntu 18.04.1 LTS**.

**Comment by roubaobaozi** [comment]
Hi, sorry for the late reply, I am trying to debug this, just haven’t found where the problem is yet.

**Comment by moabel** [comment]
![image](https://user-images.githubusercontent.com/37572525/48159127-273afa00-e2b3-11e8-9de2-64ae02bc4c6b.png)
Same here
I'm using VS Code 1.28.2 on Windows 10.
(I'm not using node.js btw, if it helps in anything)

**Comment by ArmandoValencia** [comment]
Im having the same exact problem. Restarted and reinstalled without luck.

**Comment by zhhlwd** [comment]
I also encountered this problem on the latest vscode:
Error:
The command 'sortConcentrically. SortConcentrically' not found
I really like this plugin and hope the author can solve this problem as soon as possible.

**Comment by neromaki** [comment]
Getting this same issue when trying to use - Is there any update on this @setek ?

**Comment by roubaobaozi** [comment]
Hi all,

Sorry I’m still struggling with this issue. In debug/normal mode it still works fine on my vscode.

I am asking someone else who has the issue to help debug this.

Are you all on vscode nightlies, or stable? Could you please report versions and OS?

**Comment by frebro** [comment]
**macOS Mojave 10.14.1
VSCode 1.29.1**

Getting error _"command 'sortConcentrically.sortConcentrically' not found"_ when running _"Sort CSS properties concentrically (undefined to bottom)"_ in an scss file.

**Comment by moabel** [comment]
Maybe this have something to do with this issue? [here](https://github.com/Microsoft/vscode/issues/15837#issuecomment-262177515)

**Comment by stovberpv** [comment]
Im having the same exact problem.
![image](https://user-images.githubusercontent.com/13037514/50789547-a2c62100-12cd-11e9-9770-16f90a3a2bac.png)

**Comment by jstebenne** [comment]
I have the same problem too

**Comment by roubaobaozi** [comment]
I’ve updated the extension, can whoever has the issue please try it now? I can’t test on my own machine because it has always worked for me.

**Comment by jstebenne** [comment]
I still have the problem. I cloned your code and I am also trying to see what is going on.

I added a test command that just print something to the console and even that command could not be found.

**Comment by roubaobaozi** [comment]
Can you try v 1.0.3 please?

**Comment by jstebenne** [comment]
I was about to make a pull request with the same fix that you did :P It works now

**Comment by roubaobaozi** [comment]
Terribly sorry everyone for the slow update on this. Hope it works well for everyone now.

**Comment by neromaki** [comment]
Confirmed working now, updated my review to reflect - Thanks for the extension!
